import { Marcellus } from "next/font/google";
import "./globals.css";
import { NextThemeProvider } from "@/providers/NextThemeProviders";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { ToastContainer } from "react-toastify";

const marcellus = Marcellus({
  weight: '400',
  variable: '--font-marcellus',
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" suppressHydrationWarning
      className={`${marcellus.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <NextThemeProvider>
          <Navbar />
          <main className="container mx-auto min-h-[50vh]">
            {children}
          </main>
          <Footer />
          <ToastContainer />
        </NextThemeProvider>
      </body>
    </html>
  );
}
